### ISSUE TITLE
Dateistruktur

### ISSUE THREAD

**Issue by Locxion** [X00LA/PhantomBot-German-Translation#1]
Hey X00LA!
Super arbeit mit der Übersetzung!
Ich war selber schon bei ca 60% (ohne Web Panel) als ich deine Übersetzung entdeckt habe.
Werd auf jedenfall bei dir mit Pullen wenn mir was an der Übersetzung auffällt. Hab 12 Bots bei mir laufen :D 

Jetzt noch eine Frage ...
Könntest du im Master branch noch die englischen sprachdatein einbauen?
Hilft vll bei neuen Phantombot Versionen wenn sich etwas größeres ändert.

greez
Locxion

**Comment by X00LA** [comment]
Danke, sitz grade am Update für Version 2.3.3. ;)
Danke dass du dich mit einbringen willst, 4 Augen sehen immer besser als 2 und 20 Finger tippen schneller als 10. ;)

Hoffe ich hab dir dadurch nicht den Spaß ;) am erstellen der Übersetzung genommen. :-D

Hm, hatte eigentlich nicht vor die englischen Dateien mit rein zu nehmen, da ich keinen Sinn darin sah. Hast aber von einer Seite Recht. Wenn jemand mithelfen will, muss er/sie sich nicht erst noch den Bot runter ziehen um mit zu übersetzen.
Werde sie mit dem nächsten Repository-Update mit hoch laden.

Grüße
X00LA
