### ISSUE TITLE
WEB 

### ISSUE THREAD

**Issue by timo5500** [X00LA/PhantomBot-German-Translation#11]
Web funktioniert nicht in der Version 2.3.9

**Comment by X00LA** [comment]
Die aktuellste Version der Übersetzung ist für die Bot Version 2.3.7.x.
Eine aktuellere Version ist noch nicht verfügbar, wird aber in den nächsten Wochen kommen.
Bitte den Thread im PhantomBot Forum im Auge behalten, um den Release nicht zu verpassen.
