### ISSUE TITLE
Fehler?

### ISSUE THREAD

**Issue by vuruba** [X00LA/PhantomBot-German-Translation#12]
Hi, wenn ich die Übersetzung rüberkopiere wie in der Einleitung lädt das Panel und lädt.
Habe auch Errors in der Konsole, sehe Bild:
![unbenauunnt](https://user-images.githubusercontent.com/22202989/32698337-3b76bb9c-c7a4-11e7-98c2-4412895cc686.PNG)

**Comment by X00LA** [comment]
Welche PhantomBot Version verwendest du?
Für mich sieht es aus, als ob du die Übersetzung der Version 2.7.3.1 für die aktuellste PhantomBot Version verwenden willst, das ist leider nicht möglich.

Ich werde in der zweiten Novemberhälfte mit der Übersetzung der neuesten PhantomBot Version anfangen und sie so schnell als möglich online bringen, dann kannst du die passende Version instalieren.

Grüße

**Comment by vuruba** [comment]
Ach soooo okey. Ja verwende die neuste Version Latest Release v2.3.9.1^^ gestern neu runtergeladen und installiert, Ich danke dir schon mal für die schnelle Antwort und für die tolle Arbeit :) freu mich auf das Update. liebe grüße
