### ISSUE TITLE
YTP Falsche Variable

### ISSUE THREAD

**Issue by DGoelles** [X00LA/PhantomBot-German-Translation#4]
In der Sprachdatei: scripts->lang->german->systems->systems-youtubeplayer.js in der Zeile 38 ist folgender Fehler vorhanden:

$.lang.register('ytplayer.command.songrequest.success', 'Dein Titel "$1", wurde zur Warteliste hinzugefügt. (Position: $3 ID: $4)');

richtig wäre es wie folgt:

$.lang.register('ytplayer.command.songrequest.success', 'Dein Titel "$1", wurde zur Warteliste hinzugefügt. (Position: $2 ID: $3)');

**Comment by X00LA** [comment]
Danke für die Meldung und deinem Fix.
Wird mit der nächsten Version veröffentlicht.
