### ISSUE TITLE
Charset Fehler

### ISSUE THREAD

**Issue by Lapotor** [X00LA/PhantomBot-German-Translation#9]
In der index.html fehlt das UTF-8 charset.
https://github.com/X00LA/PhantomBot-German-Translation/blob/master/web/index.html#L4
Darunter muss ein `<meta charset="utf-8">` da sonst das `Ü` Falsch dargestellt wird: `Ãœ`

**Comment by X00LA** [comment]
Danke für den Hinweis, wird in der nächsten Version behoben.
